.TH nino 1 engine "November 25, 2012" "Version 0.1"  
.SH NAME 
 nino - CECP/winboard chess engine
.SH SYNOPSIS
.B nino [\-h] [\-m mode] [\-tt transposition_table_size] [\-book file] [\-time time_controls]
.SH DESCRIPTION
Nino is a chess engine named after my cat. It suports CECP and plays under xboard and winboard.
.SH OPTIONS
.TP
\-h
display a short help text.
.TP
\-v
display engine version information.
.TP
\-tt size
set the amount of memory (in bytes) to asign to the transposition table. If zero the tt is turned off.
.TP
\-pt size
set the amount of memory (in bytes) to asign to the pawn table. If zero no pt is used.
.TP
\-book file
uses "file" as openning book
.SH AUTHOR
Alfredo Luzon (alfredoluzon@hotmail.com; allfre2luzon@gmail.com; alfredo@alfredoluzon.com)
.PP
www.alfredoluzon.com
.SH WEBSITE
www.alfredoluzon.com/nino
